# Making imports

In [1]:
import json
import numpy as np
import pandas as pd

import utils as f
from sncf_connection import SNCF

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
%aimport sncf_connection
%aimport utils

In [16]:
sncf = SNCF()

In [42]:
sncf.print_test()

tooto

# Analysis

In [10]:
df = sncf.get_dataset_df('objets-trouves-restitution')

In [11]:
df.head()

                        date gc_obo_date_heure_restitution_c  ... gc_obo_nom_recordtype_sc_c                                      gc_obo_type_c
0  2014-03-09T13:25:29+00:00                             NaN  ...               Objet trouvé                              Vêtements, chaussures
1  2018-02-06T14:35:49+00:00                             NaN  ...               Objet trouvé                 Clés, porte-clés, badge magnétique
2  2014-03-09T15:01:52+00:00                             NaN  ...               Objet trouvé                Bagagerie: sacs, valises, cartables
3  2018-02-07T10:31:12+00:00       2018-02-08T16:00:33+00:00  ...               Objet trouvé       Porte-monnaie / portefeuille, argent, titres
4  2014-03-10T09:32:18+00:00       2014-03-25T09:18:40+00:00  ...               Objet trouvé  Appareils électroniques, informatiques, appare...

[5 rows x 7 columns]

In [20]:
f.DATA_PATH

'/Users/thibaud/Documents/Data/SNCF/'

In [22]:
file_name = 'regularite-mensuelle-tgv-aqst.csv'
file_path = f.DATA_PATH + 'csv/' + file_name
df = pd.read_csv(file_path, sep=';')
df.head()

   Année  Mois Service  ... Retard à cause matériel roulant Retard à cause gestion en gare et réutilisation de matériel  Retard à cause prise en compte voyageurs
0   2018   3.0     NaN  ...                       16.883117                                           6.493506                                           3.896104
1   2018   3.0     NaN  ...                       33.333333                                           2.564103                                           0.000000
2   2018   3.0     NaN  ...                       23.529412                                          15.686275                                           1.960784
3   2018   3.0     NaN  ...                       10.000000                                          15.000000                                           0.000000
4   2018   8.0     NaN  ...                       29.629630                                          11.111111                                           7.407407

[5 rows x 34 columns]

In [33]:
(df.groupby(['Gare de départ' , 'Gare d\'arrivée'])
 .agg({'Nombre de trains annulés':'sum','Retard moyen des trains en retard à l\'arrivée (min)':'mean'})
 .sort_values(by='Retard moyen des trains en retard à l\'arrivée (min)', ascending=False)
 .head()
)

                                           Nombre de trains annulés  Retard moyen des trains en retard à l'arrivée (min)
Gare de départ       Gare d'arrivée
MARSEILLE ST CHARLES MADRID                                    54.0                                          57.108676
PARIS LYON           BARCELONA                                 32.0                                          51.751809
MADRID               MARSEILLE ST CHARLES                      58.0                                          50.672476
MARSEILLE ST CHARLES TOURCOING                                 22.0                                          48.844494
BARCELONA            PARIS LYON                                45.0                                          48.694632

In [41]:
col = 'Retard moyen des trains en retard au départ (min)'
df[df[col] == df[col].max()]

      Année  Mois  ... Retard à cause gestion en gare et réutilisation de matériel Retard à cause prise en compte voyageurs
4051   2019   4.0  ...                                          16.666667                                               0.0

[1 rows x 34 columns]